version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 49153:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    db_data:
      driver: local
